parameters:
- name: engineVersion
  type: string
- name: platform
  type: string
- name: releaseVersion
  type: string

steps:
- script: |
    mkdir "$(Build.SourcesDirectory)\ThirdParty\SDL2\${{ parameters.platform }}"
    copy "$(EpicGamesDirectory)\SDL\UE_${{ parameters.engineVersion }}\${{ parameters.platform }}\SDL2.dll" "$(Build.SourcesDirectory)\ThirdParty\SDL2\${{ parameters.platform }}\SDL2.dll"
    copy "$(EpicGamesDirectory)\SDL\UE_${{ parameters.engineVersion }}\${{ parameters.platform }}\SDL2.lib" "$(Build.SourcesDirectory)\ThirdParty\SDL2\${{ parameters.platform }}\SDL2.lib"
  displayName: 'Copy dll and lib to Plugin - ${{ parameters.engineVersion }} ${{ parameters.platform }}'
- script: '"$(LauncherDirectory)\UE_${{ parameters.engineVersion }}\Engine\Build\BatchFiles\RunUAT.bat" BuildPlugin -TargetPlatforms=${{ parameters.platform }} -Plugin=$(Build.SourcesDirectory)\JoystickPlugin.uplugin -Package=$(Build.StagingDirectory)/build/UE_${{ parameters.engineVersion }} -rocket'
  displayName: 'Build Plugin - ${{ parameters.engineVersion }} ${{ parameters.platform }}'
- task: ArchiveFiles@2
  displayName: 'Archive Plugin - ${{ parameters.engineVersion }} ${{ parameters.platform }}'
  inputs:
    rootFolderOrFile: '$(Build.StagingDirectory)/build/UE_${{ parameters.engineVersion }}'
    includeRootFolder: false
    archiveFile: '$(Build.StagingDirectory)/output/JoystickPlugin-${{ parameters.engineVersion }}-${{ parameters.platform }}-${{ parameters.releaseVersion }}.zip'
- task: ArchiveFiles@2
  displayName: 'Archive SDL - ${{ parameters.engineVersion }} ${{ parameters.platform }}'
  inputs:
    rootFolderOrFile: '$(EpicGamesDirectory)\SDL\UE_${{ parameters.engineVersion }}\${{ parameters.platform }}'
    archiveFile: '$(Build.StagingDirectory)/output/SDL-${{ parameters.engineVersion }}-${{ parameters.platform }}.zip'