name: package

inputs:
  engineVersion:
    type: string
  platform:
    type: string
  releaseVersion: releaseVersion
    type: string

runs:
  using: "composite"
  steps:
  - name: Copy dll and lib to Plugin - ${{ inputs.engineVersion }} ${{ inputs.platform }}
    run: |
    mkdir "$(Build.SourcesDirectory)\ThirdParty\SDL2\${{ inputs.platform }}"
    copy /b/v/y "$(EpicGamesDirectory)\SDL\UE_${{ inputs.engineVersion }}\${{ inputs.platform }}\SDL2.dll" "$(Build.SourcesDirectory)\ThirdParty\SDL2\${{ inputs.platform }}\SDL2.dll"
    copy /b/v/y "$(EpicGamesDirectory)\SDL\UE_${{ inputs.engineVersion }}\${{ inputs.platform }}\SDL2.lib" "$(Build.SourcesDirectory)\ThirdParty\SDL2\${{ inputs.platform }}\SDL2.lib"
  - name: 'Build Plugin - ${{ inputs.engineVersion }} ${{ inputs.platform }}'
    run: '"$(LauncherDirectory)\UE_${{ inputs.engineVersion }}\Engine\Build\BatchFiles\RunUAT.bat" BuildPlugin -TargetPlatforms=${{ inputs.platform }} -Plugin=$(Build.SourcesDirectory)\JoystickPlugin.uplugin -Package=$(Build.StagingDirectory)/build/UE_${{ inputs.engineVersion }} -rocket'