jobs:
- job: SetupVersioning
  displayName: Setup Versioning
  steps:
  - checkout: self
    persistCredentials: true
  - task: gitversion/setup@0
    displayName: "GitVersion Setup"
    inputs:
      versionSpec: '5.x'
  - task: gitversion/execute@0
    displayName: "GitVersion Execute"
    inputs:
      configFilePath: '$(Build.SourcesDirectory)\.azure-devops\GitVersion.yml'