jobs:
- job: SetupVersioning
  displayName: Setup Versioning
  steps:
  - checkout: self
    persistCredentials: true
  - task: gitversion/setup@0
    displayName: "GitVersion Setup"
    inputs:
      versionSpec: '5.x'
  - task: gitversion/execute@0
    displayName: "GitVersion Show Config"
    inputs:
      targetPath: '$(Build.SourcesDirectory)\.azure-devops\'
      useConfigFile: true
      configFilePath: 'GitVersion.yml'
      additionalArguments: '/showConfig'
  - task: gitversion/execute@0
    displayName: "GitVersion Execute"
    inputs:
      targetPath: '$(Build.SourcesDirectory)\.azure-devops\'
      useConfigFile: true
      configFilePath: 'GitVersion.yml'