name: version

runs:
  using: "composite"
  steps:
  - name: Install GitVersion
    uses: gittools/actions/gitversion/setup@v0.9.7
    with:
      versionSpec: '5.x'
      includePrerelease: true
  - name: Determine Version
    uses: gittools/actions/gitversion/execute@v0.9.7
    with:
      useConfigFile: true