name: package

inputs:
  engineVersion:
    type: string
  platform:
    type: string
  releaseVersion:
    type: string
  epicGamesDirectory:
    type: string
  launcherDirectory:
    type: string

runs:
  using: "composite"
  steps:
  - name: Copy dll and lib to Plugin - ${{ inputs.engineVersion }} ${{ inputs.platform }}
    run: |
      mkdir "$GITHUB_WORKSPACE\ThirdParty\SDL2\${{ inputs.platform }}"
      copy /b/v/y "${{ inputs.epicGamesDirectory }}\SDL\UE_${{ inputs.engineVersion }}\${{ inputs.platform }}\SDL2.dll" "$GITHUB_WORKSPACE\ThirdParty\SDL2\${{ inputs.platform }}\SDL2.dll"
      copy /b/v/y "${{ inputs.epicGamesDirectory }}\SDL\UE_${{ inputs.engineVersion }}\${{ inputs.platform }}\SDL2.lib" "$GITHUB_WORKSPACE\ThirdParty\SDL2\${{ inputs.platform }}\SDL2.lib"
    shell: cmd
  - name: 'Build Plugin - ${{ inputs.engineVersion }} ${{ inputs.platform }}'
    run: '"${{ inputs.launcherDirectory }}\UE_${{ inputs.engineVersion }}\Engine\Build\BatchFiles\RunUAT.bat" BuildPlugin -TargetPlatforms=${{ inputs.platform }} -Plugin=$GITHUB_WORKSPACE\JoystickPlugin.uplugin -Package=$(Build.StagingDirectory)/build/UE_${{ inputs.engineVersion }} -rocket'
    shell: cmd