name: package

inputs:
  engineVersion:
    type: string
  platform:
    type: string
  releaseVersion:
    type: string
  epicGamesDirectory:
    type: string
  launcherDirectory:
    type: string

runs:
  using: "composite"
  steps:
  - name: Copy dll and lib to Plugin - ${{ inputs.engineVersion }} ${{ inputs.platform }}
    run: |
      mkdir "${{ github.workspace }}\ThirdParty\SDL2\${{ inputs.platform }}"
      copy /b/v/y "${{ inputs.epicGamesDirectory }}\SDL\UE_${{ inputs.engineVersion }}\${{ inputs.platform }}\SDL2.dll" "${{ github.workspace }}\ThirdParty\SDL2\${{ inputs.platform }}\SDL2.dll"
      copy /b/v/y "${{ inputs.epicGamesDirectory }}\SDL\UE_${{ inputs.engineVersion }}\${{ inputs.platform }}\SDL2.lib" "${{ github.workspace }}\ThirdParty\SDL2\${{ inputs.platform }}\SDL2.lib"
    shell: cmd
  - name: Build Plugin - ${{ inputs.engineVersion }} ${{ inputs.platform }}
    run: '"${{ inputs.launcherDirectory }}\UE_${{ inputs.engineVersion }}\Engine\Build\BatchFiles\RunUAT.bat" BuildPlugin -TargetPlatforms=${{ inputs.platform }} -Plugin=${{ github.workspace }}\JoystickPlugin.uplugin -Package=${{ runner.temp }}/build/UE_${{ inputs.engineVersion }} -rocket'
    shell: cmd
  - name: Archive Plugin - ${{ inputs.engineVersion }} ${{ inputs.platform }}
    run: |
      $OutputFolder = "${{ runner.temp }}/output"
      if (-Not(Test-Path $OutputFolder)) {
        New-Item $OutputFolder -ItemType Directory
      }
      Compress-Archive -Path "${{ runner.temp }}/build/UE_${{ inputs.engineVersion }}/*" -DestinationPath "$OutputFolder/JoystickPlugin-${{ inputs.engineVersion }}-${{ inputs.platform }}.zip"
    shell: pwsh
  - name: Archive SDL - ${{ inputs.engineVersion }} ${{ inputs.platform }}
    run: 'Compress-Archive -Path "${{ inputs.epicGamesDirectory }}/SDL/UE_${{ inputs.engineVersion }}/${{ inputs.platform }}/*" -DestinationPath "${{ runner.temp }}/output/SDL-${{ inputs.engineVersion }}-${{ inputs.platform }}.zip"'
    shell: pwsh