name: release-plugin
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release-plugin:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Versioning
      uses: ./.github/actions/version
    - name: Package Plugin - 4.25
      uses: ./.github/actions/package
      with:
        platform: Win64
        engineVersion: '4.25'
        releaseVersion: $(Build.BuildNumber)
    - name: Package Plugin - 4.26
      uses: ./.github/actions/package
      with:
        platform: Win64
        engineVersion: '4.26'
        releaseVersion: $(Build.BuildNumber)
    - name: Package Plugin - 4.27
      uses: ./.github/actions/package
      with:
        platform: Win64
        engineVersion: '4.27'
        releaseVersion: $(Build.BuildNumber)
